### ISSUE TITLE
I cannot get it to work

### ISSUE THREAD

**Issue by networksolution** [ohh2ahh/AppAvailability#16]
Hi. In my setup the plugin is not working. I verified that the object AppAvailability is undefined.

I tried the sample code provided in the docs, but I cannot get it to work due to the AppAvailability object undefined. I was able to get other plugins working, so it might not be a general issue.

I am missing something obvious with your plugin? I'm using PhoneGap Build service.

I also opened a thread on Adobe PhoneGap Build forum: http://community.phonegap.com/nitobi/topics/appavailability-wont-work

**Comment by ohh2ahh** [comment]
Hi @networksolution. Unfortunately I can't reproduce your problem with PhoneGap Build 3.6.3 and AppAvailability 0.3.1.
* Which platform and versions do you use?
* Did you reference the plugin in your `config.xml` with `<gap:plugin name="com.ohh2ahh.plugins.appavailability" version="0.3.1" />`?
* Are you using the new code introduced in AppAvailability 0.3.1?
* Can you send me an example project with your problem?

**Comment by ohh2ahh** [comment]
I've made a repository with a demo app showing AppAvailability in action:
https://github.com/ohh2ahh/AppAvailability-Demo-PhoneGap-Build

I've tested it successfully with:
* PhoneGap 3.6.3
* iPhone 6, iOS 8.1.3
* Nexus 5, Android 5.0.1
