### ISSUE TITLE
Does this work with IOS 8?

### ISSUE THREAD

**Issue by JohnMcAvinue** [ohh2ahh/AppAvailability#17]
Hi,

I've installed the plugin via Phonegap build using the following:

<gap:plugin name="com.ohh2ahh.plugins.appavailability" version="0.3.1" />

I'm getting no errors and I can see the JS file when debugging.

I'm using this code:

        var fbCheck = "";
        var twitterCheck = "";

        if (window.device.platform == "ios") {
            fbCheck = 'fb://';
            twitterCheck = "twitter://";
        } else {
            fbCheck = 'com.facebook.katana';
            twitterCheck = "com.twitter.android";
        }
        appAvailability.checkBool(fbCheck, function (availability) {
            // availability is either true or false
            self.hasFacebookNativeApp(availability);
            alert("Has Facebook Native App " + availability);
        });
        appAvailability.checkBool(twitterCheck, function (availability) {
            // availability is either true or false
            self.hasTwitterNativeApp(availability);
            alert("Has Twitter Native App " + availability);
        });

When I run this on an iPhone 6 with IOS 8 and Facebook & Twitter Native apps installed the availability is false. I also tried using the new method with callbacks and it was the same.

I have confirmed that I can open a profile with fb://profile so it should work.

Am I missing something here or does the plugin not work with IOS 8?

**Comment by matiassingers** [comment]
The bundle identifiers you are checking with are for Android. On iOS for example Facebook's bundle identifier is `com.facebook.Facebook`, same with the Twitter bundle ID you are testing with.

**Comment by JohnMcAvinue** [comment]
Sorry but I think you're wrong. As I said, I tried opening a link with fb://profile on IOS and it worked.

The documentation on https://github.com/ohh2ahh/AppAvailability also indicates that twitter is twitter://

**Comment by ohh2ahh** [comment]
The URI schemes and bundle identifiers are correct. But are your `if and else` statements correct? Shouldn't they be somehow like this?

```js
if(device.platform === 'iOS') {
    fbCheck = 'fb://';
    twitterCheck = "twitter://";
}
else {
    fbCheck = 'com.facebook.katana';
    twitterCheck = "com.twitter.android";
}
```

I've tested the plugin again with PhoneGap Build and couldn't find any errors. Here is the repository with a demo app showing AppAvailability in action:
https://github.com/ohh2ahh/AppAvailability-Demo-PhoneGap-Build

It runs successfully with:
* PhoneGap 3.6.3
* iPhone 6, iOS 8.1.3
* Nexus 5, Android 5.0.1

**Comment by JohnMcAvinue** [comment]
Thanks for sharing that project. There was nothing wrong with the if/else other than the case of the comparison being incorrect. 

I have it working now, many thanks!

**Comment by matiassingers** [comment]
@JohnMcAvinue sorry about that, completely didn't see your conditional the first time I looked at the example just saw `com.facebook.katana` and thought Android bundle ids.
