### ISSUE TITLE
Publish the plugin on the Apache Cordova Registry

### ISSUE THREAD

**Issue by bgaillard** [ohh2ahh/AppAvailability#18]
Hi, it seems the plugin is published on the Adobe Phonegap Build Registry but is not published on the Apache Cordova Registry. 

So we can build our project on Phonegap Build but not directly using the Apache Cordova CLI tools. 

See also the following links : 
 * Plugin not available on Apache Cordova Registry http://plugins.cordova.io/#/search?search=appavailability
 * An issue I created in the Phonegap Build forums http://community.phonegap.com/nitobi/topics/some-plugins-found-in-the-phonegap-build-search-engine-are-not-available-in-the-cordova-registry

Thanks.

**Comment by ohh2ahh** [comment]
Thank you @bgaillard for your feedback. I've published the lastest version of AppAvailability to the Cordova Plugin Registry:
http://plugins.cordova.io/#/package/com.ohh2ahh.plugins.appavailability

```
cordova plugin add com.ohh2ahh.plugins.appavailability
```

I'd be thankful if you could leave a note on the PhoneGap Build forum that AppAvailability is now registered in the Cordova Plugin Registry.

**Comment by bgaillard** [comment]
Hi @ohh2ahh and thanks for your reactivity ! 

I published a message here on the Phonegap Build forum to indicate the availability of the plugin in the Apache Cordova Registry : http://community.phonegap.com/nitobi/topics/some-plugins-found-in-the-phonegap-build-search-engine-are-not-available-in-the-cordova-registry

**Comment by ohh2ahh** [comment]
Thank you, that's perfect :)
