### ISSUE TITLE
Unsupported class version number [52] (maximum 51.0, Java 1.7)

### ISSUE THREAD

**Issue by jvelez76** [ohh2ahh/AppAvailability#19]
Android
Apache Cordova 4.2
Android Studio 1.1.0
Java 1.8

Error:ProGuard: [PMRadio] Caused by: java.io.IOException: Can't process class [com/ohh2ahh/appavailability/AppAvailability.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7))

**Comment by ohh2ahh** [comment]
Hi @jvelez76 

Unfortunately I don't use and know Android Studio. Did you already try the plugin with a fresh project and Java 1.7?
