### ISSUE TITLE
iOS 9 and iOS 10: -canOpenURL: failed for URL

### ISSUE THREAD

**Issue by ohh2ahh** [ohh2ahh/AppAvailability#22]
**AppAvailability Bug**
`appAvailability.check` returns alway error callback.

**Xcode error**
`-canOpenURL: failed for URL: "<scheme>://" - error: "This app is not allowed to query for scheme <scheme>"`

**Explanation**
Apple changed the `canOpenURL` method on iOS 9. Apps which are checking for URL Schemes on iOS 9 and iOS 10 have to declare these Schemes as it is submitted to Apple. The article [Quick Take on iOS 9 URL Scheme Changes](http://awkwardhare.com/post/121196006730/quick-take-on-ios-9-url-scheme-changes) expains the changes in detail.

**Solution: Add URL Schemes to the Whitelist**
Simply open your app's .plist (usually `platforms/ios/<appname>/<appname>-Info.plist)` with an editor and add the following code with your needed Schemes.

```xml
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>twitter</string>
    <string>whatsapp</string>
</array>
```

**Comment by jason-engage** [comment]
thanks for the heads up

**Comment by ohh2ahh** [comment]
Did you edit your Info.plist?

**Comment by jason-engage** [comment]
Yeah I added the code you provided to my plist (and read that link thx). Haven't tested it yet on ios9 tho.

**Comment by ohh2ahh** [comment]
Ah, sorry. I tought that you had trouble implementing it :)

**Comment by J-Hong** [comment]
Thank your help!

**Comment by seasun** [comment]
how i do if urlschemes are from server .

**Comment by ohh2ahh** [comment]
I suppose you still have to include the schemes in your Info.plist when you're adding new schmeses serve-side (at least if you've built your app with the iOS 9 SDK on Xcode 7).

As an alternative you could use the new Universal Links for iOS 9. Or you could build the app with the old SDK using Xcode 6 until Apple forces you to use Xcode 7. There's no need for scheme registration using Xcode 6.

**Comment by babydance** [comment]
Thank your help! But I used paypal , which sschemes should I add to  LSApplicationQueriesSchemes.

**Comment by ohh2ahh** [comment]
@babydance 
Paypal's URL scheme is `paypal://`, simply add this string without `://`.

```xml
<key>LSApplicationQueriesSchemes</key>
<array>
    <string>paypal</string>
</array>
```

**Comment by babydance** [comment]
@ohh2ahh 
I had add paypal scheme just like you said ,but also doesn't work

**Comment by ohh2ahh** [comment]
@babydance 
* What is not working?
* What versions are you using (iOS, Xcode, AppAvailability)
* Is there an error in Xcode or in the console?

**Comment by seasun** [comment]
@ohh2ahh 
thanks ohh2ahh!  Because of this , so I can not upgrade. Server's urlschemes are third-party support.

**Comment by babydance** [comment]
@ohh2ahh 
thanks ohh2ahh! I upgrade the apypal sdk,and then everything is ok!

**Comment by ohh2ahh** [comment]
@babydance 
I agree that Apple's privacy measures make an upgrade complicated. Hopefully third-party apps adopt the new universal links quickly.

**Comment by rjhilgefort** [comment]
For anyone working with an app where you can't know what might be linked to, I created a plugin to work around the issue. It's a simple plugin that injects a whitelist that covers commonly linked apps. Send me a PR if I forgot any.

https://github.com/rjhilgefort/cordova-plugin-queries-schemes

**Comment by electrobabe** [comment]
had the same problem (iOS 9.2.1 with XCode 7.2.1) and needed to fix
    <allow-navigation href="uber://*/*" />
    <allow-navigation href="foursquare://*/*" />

**Comment by ramogundogdu** [comment]
where can i get the scheme of following ios app?: google hangouts, skype, ios mail app, my files, photo gallery and the scheme of on ios device installed apps?

**Comment by ohh2ahh** [comment]
@ramogundogdu Unfortunately there isn't a complete register with url schemes of popular apps. You can find known schemes of popular apps via a search engine.

**Comment by rolinger** [comment]
AppAvailability is working for me in Android - it opens right into the app.  But on iOS its failing and thus gong to the company website.  I have a hunch its the way I am calling the deeplink for iOS but can't find a better example to show me what I am doing wrong:

Example app:
```
if (dev==='iOS') { 
  scheme = "lyft://";
} else { 
  scheme = "me.lyft.android" ; //"lyft://" ;
}

var deepLink = "lyft:// ;
var url = "https://m.lyft.com/" ;

  appAvailability.check(
    scheme,
    function() {      // app is available
      window.open(deepLink,'_system','location=no') ;
    }, function () {  // app is not available, open website link
      window.open(url,'_system','location=no') ;
    }
  );
```

**Comment by ohh2ahh** [comment]
@rolinger 

Are you testing your app on an actual iOS device with Lyft installed? Which iOS version are you running? And did you add
```xml
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>lyft</string>
</array>
```
in `platforms/ios/<appname>/<appname>-Info.plist`?

**Comment by rolinger** [comment]
No....I did not have that in the -Info.plist file.  My app is in beta test right now and all my iOS users are experiencing the same issue on their devices.  All my testers are 9.2 or 9.3 (I think).

the LSApplicationQueriesSchemes already existed so all I need to do is just add the `<string>` correct?  Does the string name have to match what is going to be defined as the `scheme`  

i.e.: `var scheme = 'fb://'`  = `<string>fb</string>` ....or does it actually need to say `Facebook`

    <key>LSApplicationQueriesSchemes</key>
    <array>
      <string>instagram</string>
      <string>lyft</string>
      <string>facebook</string>
    </array>
    <key>LSRequiresIPhoneOS</key>

**Comment by ohh2ahh** [comment]
@rolinger 
Yes, since iOS 9.0 you have to add a string manually to the plist **for each URL scheme you're using** (see the explanation in my first comment). The string is the URL scheme without `://`. This should work:
```xml
<key>LSApplicationQueriesSchemes</key>
<array>
  <string>instagram</string>
  <string>lyft</string>
  <string>fb</string>
</array>
```

**Comment by rolinger** [comment]
Oh, I did read that previously but misunderstood it for something else.  Getting it all added now, thanks
