### ISSUE TITLE
Can this plugin help me to check if the app is installed?

### ISSUE THREAD

**Issue by zigzag-way** [ohh2ahh/AppAvailability#24]
I need smth like this:
http://stackoverflow.com/questions/32782178/check-if-a-particular-app-is-installed-or-launched-on-ios-9/32784078#32784078

Does this app works in this case?

**Comment by ohh2ahh** [comment]
You can't get a list with all installed apps with this plugin. Unfortunately, I don't know how to achieve this either.

**Comment by zigzag-way** [comment]
I see about th list, but what if I want to just check for a presence of a particular app (any app)?

**Comment by ohh2ahh** [comment]
Yes, that is possible if the app supports an URI scheme (e.g. Facebook's scheme is `fb://` on iOS). On Android you need the app's package name. [Here are some examples](https://github.com/ohh2ahh/AppAvailability#3-usage).

**Comment by zigzag-way** [comment]
My only q-n is about ios9. And I know that it`s done NOT using URI schemes because they can check using this way any app. So there is another way...

**Comment by ohh2ahh** [comment]
Read this for iOS 9: https://github.com/ohh2ahh/AppAvailability/issues/22

Another way could  be perfectly possible. I'm just not aware of any...
