### ISSUE TITLE
Change .Info.plist to config.xml

### ISSUE THREAD

**Issue by ptarjan** [ohh2ahh/AppAvailability#25]
Can you add a section in `config.xml` that specifies what links I want to query for and then put those in my Info.plist automatically? Editing the plist on every one of my developer's machines is not ideal.

**Comment by ohh2ahh** [comment]
That's a good idea! I'm definitely looking forward to implementing this (after I investigated the technical aspect). Thanks.

**Comment by ohh2ahh** [comment]
A quick update:
I'am afraid that I can't provide this functionality in the near future, because I don't have the time to learn more about the possibilities. PR are welcome.

**Comment by faceleg** [comment]
@ptarjan use something like this: https://github.com/driftyco/ionic-package-hooks/blob/master/ios9_allow_native_fb.sh

@ohh2ahh recommend closing this as it's not the responsibility of the plugin to perform these actions.
