### ISSUE TITLE
Linking to Facebook

### ISSUE THREAD

**Issue by vjamesv** [ohh2ahh/AppAvailability#26]
I am trying to get the facebook id for a large number of people. I can do it using a site like http://findmyfbid.com/ which is great to get one, but I need to get it for several hundred.

This is for an app, I am using cordova, and I am trying to get the appavailability plugin to work so that when someone clicks on a facebook link it will open the link in the facebook app instead of a browser. The plugin works great, but if I use the link as facebook.com/username, it will open the facebook app but just to my personal feed. If I use facebook.com/(facebook id number), it will open correctly to the the user's page.

I think my solution is to be able to get the id's for everyone and just use those as a link. It would be fine if I could get the username link to work somehow with appavailability. I am using the code from this question: http://stackoverflow.com/questions/23095906/how-to-open-twitter-and-facebook-app-with-phonegap

**Comment by ohh2ahh** [comment]
The purpose of this plugin is to check if a specific app is installed. In your case to check if the facebook app is installed. It would be wrong to include the functionality of getting user IDs in this plugin. Maybe the [Apache Cordova Facebook Plugin](https://github.com/Wizcorp/phonegap-facebook-plugin) can help you.
