### ISSUE TITLE
iOS 9.2 

### ISSUE THREAD

**Issue by galbrenner1** [ohh2ahh/AppAvailability#28]
I am having problems to detect apps, the only one that is detected is apple maps. For example I try with twitter, google maps and waze and non of them get to the success function.The schemas that I tried are : waze:// , twitter:// and comgooglemaps:// 

Do you have any idea what might be the issue?

**Comment by ohh2ahh** [comment]
Hi @galbrenner1 
Did you add the schemes to the whitelist as described [here](https://github.com/ohh2ahh/AppAvailability/issues/22)?

**Comment by galbrenner1** [comment]
Hi!
Thank you very much! it was that! :)

2016-04-03 17:59 GMT-03:00 ohh2ahh <notifications@github.com>:
