### ISSUE TITLE
appAvailability is not defined

### ISSUE THREAD

**Issue by RegencySoftware** [ohh2ahh/AppAvailability#30]
I have used this wonderful plug-in on a couple of Android apps.

Recently I noticed I was getting the following error "appAvailability is not defined"

After researching it, I found that it is happening on Android 6+.  When I install the app on Android 5 it works.

Any ideas how to correct this issue?

**Comment by ohh2ahh** [comment]
Unfortunately I don't have a device which is compatible with Android 6 at the moment. I've tested the plugin in the emulator running Android 6.0.0 and it worked for me with a fresh Cordova project.

Which Cordova CLI and Cordova Android platform are you using?

My setup: Cordova CLI 6.2.0, Cordova Android platform 5.1.1

**Comment by RegencySoftware** [comment]
I appreciate your response.

Setup: Cordova cli-5.2.0 and Android 6.0.1

I will upgrade to CLI 6.2.0 and see how it goes.
