### ISSUE TITLE
Checking an app NOT installed always invoke the success callback on IOS

### ISSUE THREAD

**Issue by jdat82** [ohh2ahh/AppAvailability#31]
Hi guys,

Did you ever experienced something similar ? Even though the app has been removed, AppAvailability still invoke the success callback. Restarting the phone doesn't change anything.

Is there a cache of some type ? I tried to remove the scheme in Info.plist, don't change anything.

```javascript
appAvailability.check(
    'http://www.bepark.eu',
    function () {  // Success callback
        // always invoked even tough the app is not installed anymore
    },
    function () {  // Error callback
        // do something
    }
);
```

Environment:
- XCode 7.3.1
- Cordova 6.3.1
- Node 5.5.0
- iOS 4.2.1

**Comment by ohh2ahh** [comment]
You have to check for the app's URL scheme (e.g. `fb://` for Facebook) instead of a simple URL. `http://www.bepark.eu` will be always true, because the URL scheme `http://` is always available.

**Comment by jdat82** [comment]
Good to know. My mistake. Work like a charm now. Thanks.
