### ISSUE TITLE
'facebook://profile/pagename' not working in android

### ISSUE THREAD

**Issue by PriyankaRose** [ohh2ahh/AppAvailability#33]
your plugin works good for twitter. But for facebook, i couldn't make the plugin to open facebook app page. instead it open the facebook feeds

```
var x = "https://www.facebook.com/McDonalds";
var array = x.split('/'); 
var nam2 = array[array.length-1];

//If Android
var ua = navigator.userAgent.toLowerCase();
var isAndroid = ua.indexOf("android") > -1; //&& ua.indexOf("mobile");

if(isAndroid) {			//alert(nam2);

appAvailability.check('com.facebook.katana', function(availability) {		//alert(availability);
    // availability is either true or false
    if(availability) {window.open('facebook://profile/'+nam2, '_system', 'location=no');}
    else{window.open(x, '_system', 'location=no');}
}, function(e) { window.open(x, '_system', 'location=no'); });

}
```

I even tried with 
facebook://pages
facebook://page

but the plugin opens the facebook app instead of facebook app page.

Any workout is appreciated.

**Comment by ohh2ahh** [comment]
Hi @PriyankaRose 
`fb://` should work.

**Comment by PriyankaRose** [comment]
fb://profile/McDonalds not working too..

do i need to use `fb://profile` or `fb://pages`?

**Comment by ohh2ahh** [comment]
`fb://page/{Facebook_Page_ID}` works for me on Android. On iOS it is `fb://page?id={Facebook_Page_ID}`.
