### ISSUE TITLE
Move this plugin to the cordova.plugins namespace

### ISSUE THREAD

**Issue by pke** [ohh2ahh/AppAvailability#35]
Thanks for this plugin!
However this plugin pollutes the global namespace. Imho it should install itself into `cordova.plugins` or just set a `isAppAvailable` or `canLaunch` on `cordova`.
This could be done with back-compatibility and a deprecation warning to the console.
If you agree I'd create a PR.

**Comment by ohh2ahh** [comment]
This is probably a good idea and I would gladly appreciate a pull request (maybe `checkAppAvailability`?). The back-compatibility would be very important of course :) Thanks!
