### ISSUE TITLE
Support scheme query on Android too

### ISSUE THREAD

**Issue by pke** [ohh2ahh/AppAvailability#36]
I'd like to add support to query the system for apps that handle a specific scheme for Android just like its possible on iOS.
This can also be done via Package Manager and an Intent query.

```java
const PackageManager manager = context.getPackageManager();
const bool appAvailable = manager.queryIntentActivities(intent, 0).size() > 0;
```

Would u accept a PR?

**Comment by ohh2ahh** [comment]
Hi @pke 
Thanks for your request. I would like to keep the plugin as simple as possible and therefore I don't think this is necessary. Thanks again!
