### ISSUE TITLE
Can't this plugin create the whitelist for us?

### ISSUE THREAD

**Issue by pke** [ohh2ahh/AppAvailability#37]
Doesn't cordova plugins support a mechanism to have config.xml variables iterated and inserted into the plist like this?

```
<platform name="ios">
    <config-file target="*-Info.plist" parent="LSApplicationQueriesSchemes">
      <array>
        <string>$SCHEME</string>
      </array>
    </config-file>
  </platform>
```
But I am not sure if plugins can do that?

**Comment by ohh2ahh** [comment]
This should work but the schemes would be hard-coded in the plugin's code. Since everyone need other schemes I find this approach suboptimal.
