### ISSUE TITLE
Not working on Android 11

### ISSUE THREAD

**Issue by naresh33** [ohh2ahh/AppAvailability#68]
Though the app installed on the device, plugin is unable to detect it. 

Ionic:

   Ionic CLI                     : 6.16.3 
   Ionic Framework               : @ionic/angular 5.6.11
   @angular-devkit/build-angular : 12.1.1
   @angular-devkit/schematics    : 12.1.1
   @angular/cli                  : 12.1.1
   @ionic/angular-toolkit        : 4.0.0

Capacitor:

   Capacitor CLI      : 3.1.1
   @capacitor/android : 3.1.2
   @capacitor/core    : 3.1.1
   @capacitor/ios     : 3.1.1

System:

   NodeJS : v14.17.3 
   npm    : 7.19.1

**Comment by henkkelder** [comment]
Its not Android 11 that is the problem, but TargetSDKVersion. Since I have set that to 30 the plugin does no longer work in Android. Reverting back to version 29 solves the problem, but doesn't really help since 30 will be neccesary soon.

**Comment by henkkelder** [comment]
Found the reason: Starting SDK 30 one cannot query all applications anymore, but most specify which application to query in AndroidManifest.xml. This resembles what is needed for IOS in the "LSApplicationQueriesSchemes" element.

I have done this via the following statement in config.xml:

`<edit-config file="AndroidManifest.xml" mode="override" target="/manifest">
            <queries>
                <package android:name="com.spotify.music" />
                <package android:name="com.opwekking.liedtekstboek" />
            </queries>
        </edit-config>`

It was however necessary to update my Android Studio and Gradle to get it working. Otherwise you will get build errors that the <queries> element is unknown.

**Comment by naresh33** [comment]
Hi @henkkelder 

Very thanks.

Adding this in AndroidManifest.xml solved the issue.

**<queries>
        <package android:name="com.opwekking.liedtekstboek"></package>
 </queries>**

**Comment by naresh33** [comment]
Hi @henkkelder

Very thanks.

Adding this in AndroidManifest.xml solved the issue.

   <queries>
        <package android:name="com.opwekking.liedtekstboek"></package>
   </queries>

**Comment by naresh33** [comment]
Hi @henkkelder

Very thanks.

<queries>
   <package android:name="com.opwekking.liedtekstboek"></package>
</queries>

Adding the above statement in AndroidManifest.xml solved the issue.

**Comment by sandhi** [comment]
if you want to get all installed app, try added this to your AndroidManifest.xml file.

```
<uses-permission android:name="android.permission.QUERY_ALL_PACKAGES" />

<queries>
    <intent>
        <action android:name="android.intent.action.MAIN" />
    </intent>
</queries>
```

I use capacitor and this work as expected, I can get all installed app on the user device.
