### ISSUE TITLE
Android 12 not work for AppAvailability

### ISSUE THREAD

**Issue by aldoexpert** [ohh2ahh/AppAvailability#71]
Please help,
are any use android 12 for this plugin ?
are this working ?
because on my android 12 is not work, always not available for check package or scheme

**Comment by secretmoo35** [comment]
I see someone add permission for browsing Package on Android 11.

https://github.com/bonbj/AppAvailability

**Comment by aldoexpert** [comment]
thanks @secretmoo35 its work
